### ISSUE TITLE
Please provide the AppImage for download

### ISSUE THREAD

**Issue by probonopd** [Or3stis/apparatus#70]
https://github.com/Or3stis/apparatus/blob/32cd196a2cf58ac2244ed38c59eb1adb0ad526e3/package.json#L34

Please provide the AppImage for download on https://github.com/Or3stis/apparatus/releases, thanks.

**Comment by Or3stis** [comment]
Thank you for using the app.

Currently, I only provide binaries for macOs and those are only for testing.

I will provide binaries for Linux and Windows on `v1.0` (see [roadmp](https://or3stis.github.io/apparatus/roadmap) for details). There are a couple of issues that need to be addressed before making the fully cross-platform.

As a temporary solution, you can compile binaries for your operating system with the `npm run dist` command. The binaries will be located in the `dist` directory.

Let me know now if you have any issues or need additional help. I would appreciate any type feedback.

**Comment by probonopd** [comment]
> Windows and Linux precompiled binaries will be added in v.1 stable. Visit the roadmap for additional details.

Thanks for having this on the roadmap. Please do ping me once it's available, then I can add it to the AppImageHub central directory of available AppImages. Keep up your great work!

**Comment by Or3stis** [comment]
After the completion of my research degree the repository is being archived.

Active development of the application has been moved to [CyberLens's](https://github.com/CyberLens/Disc0very) repository. 

After some internal changes in the architecture of the application, we will release binaries for all the supported operating systems.
